# Set theme on HA start
- alias: Set theme at startup
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: slate
- id: study_dimmer_on
  alias: Switch On Study Lights
  trigger:
  - platform: state
    entity_id: binary_sensor.osram_lightify_dimming_switch_00e91005_1
  condition:
    condition: template
    value_template: "{% set from = trigger.from_state.attributes.level | float %}\
      \ {% set to = trigger.to_state.attributes.level | float %} {{ to > from }} \n"
  action:
  - data:
      entity_id:
      - light.linear_lb60z_1_dimmable_led_light_bulb_level_3
      - light.linear_lb60z_1_dimmable_led_light_bulb_level_4
      brightness_pct: 100
    service: light.turn_on
- id: study_dimmer_off
  alias: Switch Off Study Lights
  trigger:
  - platform: state
    entity_id: binary_sensor.osram_lightify_dimming_switch_00e91005_1
  condition:
    condition: template
    value_template: "{% set from = trigger.from_state.attributes.level | float %}\
      \ {% set to = trigger.to_state.attributes.level | float %} {{ to < from }} \n"
  action:
  - data:
      entity_id:
      - light.linear_lb60z_1_dimmable_led_light_bulb_level_3
      - light.linear_lb60z_1_dimmable_led_light_bulb_level_4
    service: light.turn_off
- id: shades_nighttime
  alias: Nighttime
  trigger:
  - below: '-2.5'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: group.all_covers
      position: 5
    service: cover.set_cover_position
#- id: lights_nighttime
#  alias: night lights
#  trigger:
#  - platform: template
#    value_template: '{{ is_state(''sensor.time'', states(''input_slider.random_hour'')|int
#      ~ '':'' ~ states(''input_slider.random_minute'')|int) }}'
#  action:
#  - alias: Back light one
#    data:
#      brightness_pct: 100
#      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level
#    service: light.turn_on
#  - alias: Back light 2
#    data:
#      brightness_pct: 100
#      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level_2
#    service: light.turn_on
#  - alias: Study light one
#    data:
#      brightness_pct: 100
#      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level_3
#    service: light.turn_on
#  - alias: Study light two
#    data:
#      brightness_pct: 100
#      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level_4
#    service: light.turn_on
#  - alias: Upstairs light
#    data:
#      brightness_pct: 100
#      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level_6
#    service: light.turn_on
- id: lights_out
  alias: Lights Out
  trigger:
  - hours: 22
    minutes: 30
    platform: time_pattern
    seconds: 33
  action:
  - data:
      entity_id: group.downstairs_lights
    service: light.turn_off
  - data:
      entity_id: group.all_covers
      position: 5
    service: cover.set_cover_position
- id: shades_dusk
  alias: Dusk
  trigger:
  - below: '-1'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: cover.graber_csz1_cellular_shade_level 
      position: 20
    service: cover.set_cover_position
  - data:
      entity_id: cover.graber_csz1_cellular_shade_level_2
      position: 25
    service: cover.set_cover_position
  - data:
      entity_id: cover.graber_csz1_cellular_shade_level_3
      position: 25
    service: cover.set_cover_position
  - data:
      entity_id: cover.graber_csz1_cellular_shade_level_4
      position: 25
    service: cover.set_cover_position
  - data:
      entity_id: cover.graber_csz1_cellular_shade_level_5
      position: 25
    service: cover.set_cover_position
  - data:
      brightness: 1
      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level_5
    service: light.turn_on
  - alias: RGB one
    data:
      brightness: 200
      color_temp: 500
      entity_id: light.ledvance_a19_rgbw_0001e17d_1
    service: light.turn_on
  - alias: Back light one
    data:
      brightness_pct: 45
      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level
    service: light.turn_on
  - alias: Back light 2
    data:
      brightness_pct: 45
      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level_2
    service: light.turn_on
- id: shades_daytime
  alias: Daytime
  trigger:
  - at: '7:25'
    platform: time
  action:
  - data:
      entity_id: cover.graber_csz1_cellular_shade_level
      position: 100
    service: cover.set_cover_position
  - data:
      entity_id: cover.graber_csz1_cellular_shade_level_2
      position: 49
    service: cover.set_cover_position
  - data:
      entity_id: cover.graber_csz1_cellular_shade_level_3
      position: 100
    service: cover.set_cover_position
  - data:
      entity_id: cover.graber_csz1_cellular_shade_level_4
      position: 100
    service: cover.set_cover_position
  - data:
      entity_id: cover.graber_csz1_cellular_shade_level_5
      position: 100
    service: cover.set_cover_position
  - data:
      entity_id: group.all_lights
    service: light.turn_off
- id: bedroom_wake_1
  alias: Wake Linda 1
  trigger:
  - at: '6:20'
    platform: time
  action:
    - service: light.turn_on
      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level_6
      data:
        brightness_pct: 33
- id: bedroom_wake_2
  alias: Wake Linda 2
  trigger:
  - at: '6:25'
    platform: time
  action:
    - service: light.turn_on
      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level_6
      data:
        brightness_pct: 66
- id: bedroom_wake_3
  alias: Wake Linda 3
  trigger:
  - at: '6:30'
    platform: time
  action:
    - service: light.turn_on
      entity_id: light.linear_lb60z_1_dimmable_led_light_bulb_level_6
      data:
        brightness_pct: 100
